name: Secure PWA Deploy

on:
  push:
    branches:
      - main

# Разрешаем этому роботу официально публиковать сайт на GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps: deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Inject Dynamic Version to Cache and HTML
        run: |
          # Используем уникальный номер прохода GitHub Actions
          BUILD_NUM="${{ github.run_number }}"
          
          # Заменяем текстовые маркеры на реальное число прямо в памяти сервера перед сборкой
          sed -i "s/BUILD_VERSION/$BUILD_NUM/g" sw.js
          sed -i "s/BUILD_VERSION/$BUILD_NUM/g" index.html
          
          echo "Сборка запущена под уникальным номером: $BUILD_NUM"

      - name: Upload Static Web Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
