name: Auto Version SW Cache

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Inject Dynamic Version into SW and HTML
        run: |
          BUILD_NUM="${{ github.run_number }}"
          
          # Жестко прописываем новый номер билда в Service Worker и разметку
          sed -i "s/BUILD_VERSION/$BUILD_NUM/g" sw.js
          sed -i "s/BUILD_VERSION/$BUILD_NUM/g" index.html
          
          echo "Сгенерирована сборка под номером: $BUILD_NUM"

      - name: Commit and Push Updated Files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          
          git add sw.js index.html
          git commit -m "chore: auto-update build version to #$GITHUB_RUN_NUMBER [skip ci]" || echo "No changes to commit"
          git push
